//EXERCICIO 1

let idade = 24

if (idade >= 18 && idade <= 25 )
{console.log ("A idade está entre 18 e 25")
}
else `A idade não está entre 18 e 25`

//EXERCICIO 2

let carroNome = "Chevrolet"
let carroAno = 2019
let filtrarCarro = (carroNome === "Chevrolet" && carroAno === 2019)

if (filtrarCarro = true){
console.log ("Carro encontrado")}
else "Carro não encontrado"

//EXERCICIO 3

let botaoMenu = false
let avaliarClick = ( botaoMenu !== false)

if (avaliarClick = true){
console.log ("fechar menu")}
else "abrir menu"